version: '3.8'

networks:
  backend:
    driver: bridge

services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    networks:
      - backend

  nginx:
    container_name: nginx-server
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - backend